---
title: "mTOR in TCGA pancancer studies"
subtitle: "preliminary exploration"
date: "Figures last updated: `r Sys.time()`"
output: html_document
params:
    html_dir: "summary"
---

***

```{r, setup, echo=F, include = F}
library(dplyr)
library(ggplot2)
library(kableExtra)
knitr::opts_chunk$set(echo = F, fig.align = 'center', out.width = '100%')
htmls <- list.files(params$html_dir, pattern = "*.html") 
htmls <- htmls[htmls != 'index.html']
```


```{r, manifest}
# wd
maf_dir <- "data"
result_dir <- "results"
manifest <- "gdc_manifest_20200722_033552.txt"

# set up manifest data 
manifest <- read.delim(manifest, stringsAsFactors=F)
manifest$cancer_type <- sapply(strsplit(manifest$filename, split = ".", fixed = T), "[[", 2)
manifest$maf_fn <- paste(maf_dir, manifest$id, manifest$filename, sep = "/")
manifest$maf_fn <- gsub('.{3}$', '', manifest$maf_fn)
manifest$caller <- sapply(strsplit(manifest$maf_fn, split = ".", fixed = T), "[[", 3)
manifest$result_fn <- paste0(result_dir, "/", manifest$id, ".sig_genes.txt")

# select a gene, return list of cancers it is significantly enriched in. 
get_p <- function(gene, file){
	tumour <- read.delim(file, stringsAsFactors=F)
	gidx <- which(tumour$gene == gene)
	return(tumour$p[gidx])
}

# plot p-values for gene g, facet by mutation caller
plot_p <- function(sig_data, g){
	sig_data$p_val <- sapply(sig_data$result_fn, get_p, gene = g)  
	g <- ( ggplot(sig_data, aes(x=cancer_type, y=p_val, colour = caller)) 
		   + geom_point()
		   + ggtitle(sprintf("%s mutation significance (MutSigCV)", g))
		   + theme_classic()
		   + theme(axis.text.x = element_text (angle = 90))
		   + geom_hline(yintercept=c(0.1, 0.05), linetype="dashed", color = c("gray72", "gray58"))
		 )
	return(g)
}
```

```{r, mutsigCV}
sig_data <- manifest[c("id", "result_fn", "cancer_type", "caller")]


# check results were generated
rm_set <- !(manifest$result_fn %in% list.files(result_dir, pattern = "*.sig_genes.txt", full.names = T))
if (sum(rm_set) > 0) { 
	warning(sprintf("%d result files missing", sum(rm_set))) 
	sig_data <- sig_data[!rm_set, ]
}

# get MTOR significance
plot_p(sig_data, "MTOR")
```

## Cancer-specific summaries (`r length(htmls)` MAF files)

```{r, copse-members}
copse <- cell_spec(unlist(strsplit(htmls, split = ".", fixed = T))[c(T,F)], "html", link = htmls)
copseTable <- knitr::kable(copse, escape = F, align = 'l', col.names = NULL)
kable_styling(copseTable, bootstrap_options = c("striped", "bordered")) %>%
	scroll_box(width = "100%", height = "400px")
```
